---
title: "Today's Electricity Consumption"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
workflowr:
  suppress_report: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE,
                      fig.width = 9, fig.height = 3)
``` 

```{r}
library(lubridate)
library(reshape2)
library(dplyr)
library(ggplot2)
library(plotly)
```

```{r}
# load data
data <- read.csv("data/electricity_2014_2022.csv")

data <- data %>%
  mutate(Year = year(date), Month = month(date), Day = day(date))

# select the data of 2022-12
data_filtered <- data %>%
  filter(Year == 2022, Month == 12, Day == 31)

data_filtered = melt(data_filtered, measure.vars = c("chambre", "consultation", "bureau"))
data_filtered = data_filtered %>%
  rename(facility = variable) %>%
  rename(electricity = value)
```


```{r eval=FALSE, fig.height=9, fig.width=9, include=FALSE}
# ggplot2 for histogram
p <- ggplot(data_filtered, aes(x = hour, y = electricity, fill = facility)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~facility, ncol = 1) +
  labs(x = "Hour", y = "Electricity (kWh)", title = "2022-12-31") +
  theme_minimal()

# using plotly
p <- ggplotly(p)

# plot
p
```


```{r}
time_save = read.csv("data/time_save_2014_2022.csv")
time_save <- time_save %>%
  mutate(Year = year(date), Month = month(date), Day = day(date))

# select the data of 2022-12
time_save_filtered <- time_save %>%
  filter(Year == 2022, Month == 12, Day == 31)

time_save_filtered = melt(time_save_filtered, measure.vars = c("chambre", "consultation", "bureau"))
time_save_filtered = time_save_filtered %>%
  rename(facility = variable) %>%
  rename(h = value)
```


# 2022-12-31 {.tabset .tabset-pills}
## chambre
```{r}
df = time_save_filtered %>% 
    filter(facility == "chambre")
df <- df %>%
  mutate(h_cum = cumsum(h))

df$euro = 20/24*0.2*df$h
df <- df %>%
  mutate(euro_cum = cumsum(euro))
```

```{r}
p <- ggplot(df, aes(x = hour, y = h)) + 
  geom_bar(stat = "identity", position = "dodge", fill = "red") +
  scale_x_continuous(breaks = 0:23) + 
  labs(x = "Hour", y = "Saving hours") +
  theme_minimal()
p <- ggplotly(p)
p 
```


```{r}
p <- ggplot(df, aes(x = hour, y = euro_cum)) + 
  geom_line(size = 1, col = "red") +
  scale_x_continuous(breaks = 0:23) + 
  labs(x = "Hour", y = "Saving Euros (€)") +
  theme_minimal()
p <- ggplotly(p)
p 
```


```{r}
temp = data_filtered %>% 
    filter(facility == "chambre")

p <- ggplot(temp, aes(x = hour, y = electricity)) +
  geom_bar(stat = "identity", position = "dodge", fill = "red") +
  scale_x_continuous(breaks = 0:23) + 
  labs(x = "Hour", y = "Electricity (kWh)", title = "") +
  theme_minimal()
p <- ggplotly(p)
p 
```


## consultation
```{r}
df = time_save_filtered %>% 
    filter(facility == "consultation")
df <- df %>%
  mutate(h_cum = cumsum(h))

df$euro = 20/24*0.2*df$h
df <- df %>%
  mutate(euro_cum = cumsum(euro))
```

```{r}
p <- ggplot(df, aes(x = hour, y = h)) + 
  geom_bar(stat = "identity", position = "dodge", fill = "green") +
  scale_x_continuous(breaks = 0:23) + 
  labs(x = "Hour", y = "Saving hours") +
  theme_minimal()
p <- ggplotly(p)
p 
```


```{r}
p <- ggplot(df, aes(x = hour, y = euro_cum)) + 
  geom_line(size = 1, col = "green") +
  scale_x_continuous(breaks = 0:23) + 
  labs(x = "Hour", y = "Saving Euros (€)") +
  theme_minimal()
p <- ggplotly(p)
p 
```


```{r}
temp = data_filtered %>% 
    filter(facility == "consultation")

p <- ggplot(temp, aes(x = hour, y = electricity)) +
  geom_bar(stat = "identity", position = "dodge", fill = "green") +
  scale_x_continuous(breaks = 0:23) + 
  labs(x = "Hour", y = "Electricity (kWh)", title = "") +
  theme_minimal()
p <- ggplotly(p)
p 
```


## bureau
```{r}
df = time_save_filtered %>% 
    filter(facility == "bureau")
df <- df %>%
  mutate(h_cum = cumsum(h))

df$euro = 20/24*0.2*df$h
df <- df %>%
  mutate(euro_cum = cumsum(euro))
```

```{r}
p <- ggplot(df, aes(x = hour, y = h)) + 
  geom_bar(stat = "identity", position = "dodge", fill = "blue") +
  scale_x_continuous(breaks = 0:23) + 
  labs(x = "Hour", y = "Saving hours") +
  theme_minimal()
p <- ggplotly(p)
p 
```


```{r}
p <- ggplot(df, aes(x = hour, y = euro_cum)) + 
  geom_line(size = 1, col = "blue") +
  scale_x_continuous(breaks = 0:23) + 
  labs(x = "Hour", y = "Saving Euros (€)") +
  theme_minimal()
p <- ggplotly(p)
p 
```


```{r}
temp = data_filtered %>% 
    filter(facility == "bureau")

p <- ggplot(temp, aes(x = hour, y = electricity)) +
  geom_bar(stat = "identity", position = "dodge", fill = "blue") +
  scale_x_continuous(breaks = 0:23) + 
  labs(x = "Hour", y = "Electricity (kWh)", title = "") +
  theme_minimal()
p <- ggplotly(p)
p 
```


