---
title: "yearly data"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)
library(ggplot2)

data = read.csv("data/yearly_data.csv")

# 创建折线图函数
create_line_plot <- function(facility) {
  plot_data <- data.frame(year = years, electricity = switch(
    facility,
    chambre = chambre_data,
    consultation = consultation_data,
    bureau = bureau_data
  ))
  
  p <- plot_ly(data = plot_data, x = ~year, y = ~electricity, type = 'scatter', mode = 'lines') %>%
    layout(title = paste("Electricity Consumption -", facility),
           xaxis = list(title = "Year"),
           yaxis = list(title = "Electricity (kWh)"),
           showlegend = FALSE)
  
  return(p)
}

# 创建数据和设施选择列表
years <- 2013:2022
chambre_data <- data$chambre
consultation_data <- data$consultation
bureau_data <- data$bureau
facility_choices <- c("chambre", "consultation", "bureau")

# 创建初始折线图
p <- create_line_plot(facility_choices[1])
p
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
# 创建初始折线图
p <- create_line_plot(facility_choices[2])
p
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# 创建初始折线图
p <- create_line_plot(facility_choices[3])
p
```
